inherit_gem: { rubocop-rails-omakase: rubocop.yml } # Omakase Ruby styling for Rails

plugins:
  - rubocop-performance 

AllCops: 
  NewCops: enable # 新しいCopsを有効にする

Rails: # Rails特有の書き方やベストプラクティスを検証
  Enabled: false

Bundler: # gemの重複などの問題を検証
  Enabled: false

Security: # セキュリティ上の危険なコードを検証
  Enabled: false

Lint: # 一般的なコードの問題を検証検証
  Enabled: false

Layout: # コードのレイアウトを検証
  Enabled: false

Style: # コーディングスタイルを検証
  Enabled: false
  
# ------------------------------ rails ------------------------------

Rails/DynamicFindBy: # generate_token_forによる定義される`find_by_token_for`で利用。
  Enabled: false

Rails/I18nLocaleTexts: # I18nの強制
  Enabled: false

Rails/NotNullColumn: # DBのNOT NULL制約が正しく設定されているか検証
  Enabled: false

Rails/InverseOf: # inverse_ofの検証
  Enabled: false
